name:  Run Trivy scan

on:
  push:
    tags:
      - '*'
  pull_request:


jobs:
  trivy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Get base image
        run: |
          image=$(grep hyperkube-base Dockerfile | awk '{ print $2 }')
          echo "HYPERKUBE=${image}"
          echo "HYPERKUBE=${image}" >> "$GITHUB_ENV"
      - name: Run Trivy scanner
        uses: aquasecurity/trivy-action@0.19.0
        with:
          image-ref:  ${{ env.HYPERKUBE }}
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
